server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: user
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
  application:
    name: api-gateway-service

logging:
  level:
    org.springframework.cloud.gateway: DEBUG