
package com.webservicemart.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "USZipSoap", targetNamespace = "http://webservicemart.com/ws/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface USZipSoap {


    /**
     * Returns United States Postal Service State Abbreviation, Latitude (decimal degrees) and Longitude (decimal degrees).
     * 
     * @param zipCode
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ValidateZip", action = "http://webservicemart.com/ws/ValidateZip")
    @WebResult(name = "ValidateZipResult", targetNamespace = "http://webservicemart.com/ws/")
    @RequestWrapper(localName = "ValidateZip", targetNamespace = "http://webservicemart.com/ws/", className = "com.webservicemart.ws.ValidateZip")
    @ResponseWrapper(localName = "ValidateZipResponse", targetNamespace = "http://webservicemart.com/ws/", className = "com.webservicemart.ws.ValidateZipResponse")
    public String validateZip(
        @WebParam(name = "ZipCode", targetNamespace = "http://webservicemart.com/ws/")
        String zipCode);

}
