//created on: 18 Mar, 2018
package demo

//list any import classes here.
import com.demo.drools.model.Message;

//declare any global variables here
global org.slf4j.Logger log;
global com.demo.drools.dao.AppLogDao appLogDao;


rule "Rule 1"
    when
        $msg : Message( text == "Hello" )
    then
        log.info("Hello ....");
        $msg.setText("Bye");
        update($msg);
        log.info("updated message ....");
        appLogDao.addLogRecord("Rule 1 execution end");
        
end

rule "Rule 2"
    when
        $msg : Message( text == "Bye" )
    then
    	log.info("Bye ....");
    	appLogDao.addLogRecord("Rule 2 execution end");
end
