spring.application.name=demo-spring-ai

# Command line only enablled.
spring.main.web-application-type=none

#### Ollama Local Server with OpenAI API specification ####
spring.ai.openai.base-url=http://localhost:11434
spring.ai.openai.api-key=<Dummy key because OpenAI SDK looks for a key at startup>
spring.ai.openai.chat.options.model=smollm2:135m
spring.ai.openai.options.model=smollm2:135m

#### Hugging Face Router with OpenAI API specification ####
#spring.ai.openai.base-url=https://router.huggingface.co
#spring.ai.openai.api-key=<Replace with your hugging face token>
#spring.ai.openai.chat.options.model=google/gemma-3-1b-it:featherless-ai
#spring.ai.openai.options.model=google/gemma-3-1b-it:featherless-ai
