spring.application.name=demo-spring-ai

# Command line only enablled.
spring.main.web-application-type=none

# Hugging Face Router with OpenAI API
# Ref: https://huggingface.co/docs/inference-endpoints/index
spring.ai.openai.base-url=https://router.huggingface.co
spring.ai.openai.api-key=<Replace with hugging face token>
spring.ai.openai.chat.options.model=google/gemma-3-1b-it:featherless-ai
spring.ai.openai.options.model=google/gemma-3-1b-it:featherless-ai

