//created on: 18 Mar, 2018
package demo

//list any import classes here.
import com.demo.drools.model.Message;

//declare any global variables here
global org.slf4j.Logger log;


rule "Rule 1"
    when
        $msg : Message( text == "Hello" )
    then
        log.info("Hello ....");
        $msg.setText("Bye");
        update($msg);
        log.info(" updated message ....");
        
end

rule "Rule 2"
    when
        $msg : Message( text == "Bye" )
    then
        log.info("Bye ....");
end
